package org.wendel.card;
// Generated by CodiumAI

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class CardTest {


    // Should create a card with a given number and suit
    @Test
    public void test_createCardWithNumberAndSuit() {
        Card card = new Card(5, Suit.SPADES);
        assertEquals(5, card.getNumber());
        assertEquals(Suit.SPADES, card.getSuit());
    }

    // Should return the number of the card
    @Test
    public void test_getNumber() {
        Card card = new Card(8, Suit.HEARTS);
        assertEquals(8, card.getNumber());
    }

    // Should return the suit of the card
    @Test
    public void test_getSuit() {
        Card card = new Card(2, Suit.CLUBS);
        assertEquals(Suit.CLUBS, card.getSuit());
    }

    // Should create a card with the number 1 and the suit SPADES
    @Test
    public void test_createCardWithNumber1AndSuitSpades() {
        Card card = new Card(1, Suit.SPADES);
        assertEquals(1, card.getNumber());
        assertEquals(Suit.SPADES, card.getSuit());
    }

    // Should create a card with the number 13 and the suit DIAMOND
    @Test
    public void test_createCardWithNumber13AndSuitDiamond() {
        Card card = new Card(13, Suit.DIAMONDS);
        assertEquals(13, card.getNumber());
        assertEquals(Suit.DIAMONDS, card.getSuit());
    }

    // Should create a card with the number 10 and the suit CLUBS
    @Test
    public void test_createCardWithNumber10AndSuitClubs() {
        Card card = new Card(10, Suit.CLUBS);
        assertEquals(10, card.getNumber());
        assertEquals(Suit.CLUBS, card.getSuit());
    }

}