return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 3,
  height = 7,
  tilewidth = 99,
  tileheight = 114,
  nextlayerid = 3,
  nextobjectid = 9,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 3,
      height = 7,
      id = 1,
      name = "card-layer",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0,
        0, 0, 0,
        0, 0, 0,
        0, 0, 0,
        0, 0, 0,
        0, 0, 0,
        0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "obj-card-layer",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          class = "c1",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          class = "c2",
          shape = "rectangle",
          x = 100,
          y = 0,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          class = "c3",
          shape = "rectangle",
          x = 199,
          y = 0,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          class = "c1",
          shape = "rectangle",
          x = 0,
          y = 115,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          class = "c2",
          shape = "rectangle",
          x = 100,
          y = 115,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          class = "c3",
          shape = "rectangle",
          x = 199,
          y = 115,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          class = "c1",
          shape = "rectangle",
          x = 0,
          y = 229,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          class = "c2",
          shape = "rectangle",
          x = 100,
          y = 229,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          class = "c3",
          shape = "rectangle",
          x = 199,
          y = 229,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          class = "c1",
          shape = "rectangle",
          x = 0,
          y = 343,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          class = "c2",
          shape = "rectangle",
          x = 100,
          y = 343,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          class = "c3",
          shape = "rectangle",
          x = 199,
          y = 343,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          class = "c1",
          shape = "rectangle",
          x = 0,
          y = 457,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          class = "c2",
          shape = "rectangle",
          x = 100,
          y = 457,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          class = "c3",
          shape = "rectangle",
          x = 199,
          y = 457,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          class = "c1",
          shape = "rectangle",
          x = 0,
          y = 571,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          class = "c2",
          shape = "rectangle",
          x = 100,
          y = 571,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          class = "c3",
          shape = "rectangle",
          x = 199,
          y = 571,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          class = "c1",
          shape = "rectangle",
          x = 0,
          y = 685,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          class = "c2",
          shape = "rectangle",
          x = 100,
          y = 685,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          class = "c3",
          shape = "rectangle",
          x = 199,
          y = 685,
          width = 99,
          height = 114,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
